### ISSUE TITLE
Change the Logo

### ISSUE THREAD

**Issue by cypherlinux** [temporary-audacity/audacity#44]
Good evening. We all know the eventual pitfall that continues to hinder FOSS (free and open-source software) programs: appearances and aesthetic touches. Audacity is a highly-functional audio recording program that has survived for a number of years due to its intuitive layout and attention to detail. However, Audacity, too, has not changed its dated logo for some time. I submit a new logo that could help rejuvenate Audacity and assist bringing this commendable software to a larger audience.

![image](https://user-images.githubusercontent.com/71843865/124529002-97d5a400-ddd7-11eb-8f03-80fecd589082.png)

**Comment by trickypr** [comment]
Please wait for a new name to be decided on in #33 before submitting a new logo

**Comment by infinitytec** [comment]
That's pretty much the Audacity logo, which is a trademark of the people that own it.

**Comment by m93a** [comment]
(Furthermore, the original logo is ugly af if you ask me)

**Comment by rand0m0User** [comment]
https://i.4cdn.org/g/1625527328874.png is a dope logo edit tho

**Comment by chaziz94** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity

already made

**Comment by cypherlinux** [comment]
Hat added for style.

![download2](https://user-images.githubusercontent.com/71843865/124529871-6c53b900-ddd9-11eb-8de4-790581a67288.png)

**Comment by Aschonberger** [comment]
![sneedacity (3)](https://user-images.githubusercontent.com/63123918/124530610-1297c280-ddca-11eb-907f-d91bde44afda.jpg)

with or without the headphones?

**Comment by cypherlinux** [comment]
![sneedacitylogo](https://user-images.githubusercontent.com/71843865/124530830-3d3e4700-dddb-11eb-905c-846ca573ea84.png)

**Comment by trickypr** [comment]
Using any part of the audacity logo for the logo of this project opens it up to legal action on the basis of trademark disputes. I highly doubt that they will become the logo for this project

**Comment by cypherlinux** [comment]
> Using any part of the audacity logo for the logo of this project opens it up to legal action on the basis of trademark disputes. I highly doubt that they will become the logo for this project

13%, >50%

**Comment by emabrey** [comment]
This person is trolling. They need to be banned and the issue needs to be closed. @cookiengineer

**Comment by emabrey** [comment]
Cipherlinux was posting images with hidden white nationalist imagery as logo requests. Issue Closed.
