### ISSUE TITLE
Who owns this repo?

### ISSUE THREAD

**Issue by awslabspl** [temporary-audacity/audacity#80]
Who is the `owner` of this repo? Who can give-out privileges?

**Comment by jeyemwey** [comment]
There is a small group of people that currently plan the governance. Please hold the line, it takes time and people have other jobs, too.

If you have a real question, please ask it here or in a new issue.

**Comment by awslabspl** [comment]
@jeyemwey Thank you :)
All I want is to ask whats their nicknames, because I need to contact them privately.

**Comment by User-green** [comment]
This seem to be cookiengineer.

**Comment by awslabspl** [comment]
> This seem to be cookiengineer.

I was asking seriously..............

**Comment by jeyemwey** [comment]
You are probably looking for Cookie, but they had a rough night and are drowning in messages. So you can probably not reach them right now.

**Comment by awslabspl** [comment]
> You are probably looking for Cookie, but they had a rough night and are drowning in messages. So you can probably not reach them right now.

All right but at lease please provide their nickname............

**Comment by peepopoggers** [comment]
Idk owners, but moderators -> #48

**Comment by EricBright** [comment]
Closed as duplicate of #28.
